general.live_config_reload = true

[font]
size = 14
# normal = { family = "IosvekaTermNerdFont" }
# bold = { family = "CommitMono Nerd Font" }
# italic = { family = "CommitMono Nerd Font" }
# bold_italic = { family = "CommitMono Nerd Font" }
# bold = { family = "JetBrains Mono NL", style = "ExtraBold" }
# italic = { family = "JetBrains Mono NL", style = "SemiBold Italic" }
# bold_italic = { family = "JetBrains Mono NL", style = "ExtraBold Italic" }
# normal = { family = "ZedMonoNerdFont" }
# bold = { family = "ZedMonoNerdFont" }
# italic = { family = "ZedMonoNerdFont" }
# bold_italic = { family = "ZedMonoNerdFont" }
normal = { family = "AdwaitaMonoNerdFont" }
bold = { family = "AdwaitaMonoNerdFont" }
italic = { family = "AdwaitaMonoNerdFont" }
bold_italic = { family = "AdwaitaMonoNerdFont" }


[window]
opacity = 0.98

[colors.primary]
background = "#141417"
