general.live_config_reload = true

[font]
size = 11
normal = { family = "JetBrains Mono NL", style = "SemiBold" }
bold = { family = "JetBrains Mono NL", style = "ExtraBold" }
italic = { family = "JetBrains Mono NL", style = "SemiBold Italic" }
bold_italic = { family = "JetBrains Mono NL", style = "ExtraBold Italic" }

[window]
# opacity = 0.8
