general.live_config_reload = true

[font]
size = 16
normal = { family = "JetBrains Mono", style = "SemiBold" }
bold = { family = "JetBrains Mono", style = "ExtraBold" }
italic = { family = "JetBrains Mono", style = "SemiBold Italic" }
bold_italic = { family = "JetBrains Mono", style = "ExtraBold Italic" }
