alias tree='eza --tree'
alias ll='ls -l --color=auto'
alias lla='ls -alF --color=auto'
alias la='ls -A --color=auto'
alias l='ls -CF --color=auto'
alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias grep='grep --color=always'
alias cpui='watch -n1 "grep \"^[c]pu MHz\" /proc/cpuinfo"'
alias ls='eza --color=always --group-directories-first --git --git-repos'
alias ll='eza -lh --color=always --group-directories-first --git --git-repos'
alias lla='eza -alhF --color=always --group-directories-first --git --git-repos'
alias la='eza -A --color=always --group-directories-first --git --git-repos'
alias mv='mv -i --backup=simple'
alias cd='z'
alias cal='cal -m'
alias vim='neovim'
